pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Directory') {
            steps {
                sh 'cd api/create-deploy'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean install'
            }
        }
    }
}