pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -v /var/jenkins/workspace/falcon-millenium/api/create-deploy/pom.xml clean install -B -DskipTests'
            }
        }
    }
}